FROM openjdk
MAINTAINER Piotr Minkowski <piotr.minkowski@gmail.com>
ADD target/personalDetails-service.jar personalDetails-service.jar
ENTRYPOINT ["java", "-jar", "/personalDetails-service.jar"]
EXPOSE 1111