info:
  component: Edge Server
  
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

zuul:
  prefix: /api
  routes:
    account: 
      path: /account/**
      serviceId: account-service
    customer: 
      path: /customer/**
      serviceId: customer-service   
      
    request: 
      path: /request/**
      serviceId: request-service 
      
    mainRequest: 
      path: /mainRequest/**
      serviceId: mainRequest-service       
            
    LoginAndRegistration:
      path: /login/**
      serviceId: loginRegistration-service
      
    personalDetails:
      path: /personalDetails/**
      serviceId: personalDetails-service

    hystrix:
      command:
        default:
          execution:
            isolation:
              thread:
                timeoutInMilliseconds: 20000 
    ribbon:
    eureka:
    enabled: true
    
 

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: false
      
server:
  port: 8765

logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG
    
    

 
    
    
    