FROM openjdk
MAINTAINER Piotr Minkowski <piotr.minkowski@gmail.com>
ADD target/loginRegistration-service.jar loginRegistration-service.jar
ENTRYPOINT ["java", "-jar", "/loginRegistration-service.jar"]
EXPOSE 9090