node {

    withMaven(maven:'maven') {

        stage('Checkout') {
            git url: 'https://github.com/piomin/sample-spring-microservices.git', credentialsId: 'github-piomin', branch: 'master'
        }

        stage('Build') {
            sh 'mvn clean install'

            def pom = readMavenPom file:'pom.xml'
            print pom.version
            env.version = pom.version
        }

        stage('Image') {
            dir ('mainRequest-service') {
                def app = docker.build "localhost:5000/mainRequest-service:${env.version}"
                app.push()
            }
        }

        stage ('Run') {
            docker.image("localhost:5000/mainRequest-service:${env.version}").run('-p 4444:4444 -h mainRequest --name mainRequest --link discovery --link account --link visa --link forex --link flight --link cab --link accommodation')
        }

        stage ('Final') {
            build job: 'gateway-service-pipeline', wait: false
        }      

    }

}